version: "3.8"

services:
  mongo_db:
    networks:
      - web_network
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    container_name: "web-database"
    command: [--auth]
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  web_app:
    depends_on:
      - mongo_db
    networks:
      - web_network
    build: .
    image: ghcr.io/greylake/web-app:latest
    restart: on-failure
    env_file: ./.env
    container_name: "web-app"
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
networks:
  web_network:
    driver: bridge

volumes:
  db: