name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build The Web Stack
        run: docker-compose up -d
      - name: Test The Web Stack
        run: docker run --network container:web-app appropriate/curl -s --retry 10 --retry-connrefused http://localhost:45080/
