name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/web-app:latest
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: GreyLake
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and Publish
      run: |
         docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
         docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
