name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/web-app:latest
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set Proper Image Name
      uses: Entepotenz/change-string-case-action@v1
      with:
        string: ${{ env.IMAGE_NAME }}
        run: echo "IMAGE_NAME=${{ steps.convert_actor.outputs.lowercase }}/web-app:latest" >> $GITHUB_ENV
    - name: Build and Publish
      run: |
         docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
         docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
