name: Docker Deploy

on:
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH Key
      uses: webfactory/ssh-agent@v0.5
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Authenticate with GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: SSH into Server and Pull Docker Image
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_PATH }} && docker-compose pull web_app && docker-compose up -d"
