name: Docker Deploy

on:
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: greylake/web-app:latest
  
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH Key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ${{ secrets.WORK_PATH }}
          docker-compose pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker-compose up -d

   

