name: Docker Deploy

on:
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: greylake/web-app:latest
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: pass multiple environment
      uses: appleboy/ssh-action@v1.0.3
      env:
        FOO: "BAR"
        BAR: "FOO"
        SHA: ${{ github.sha }}
        PORT: ${{ secrets.PORT }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: FOO,BAR,SHA,PORT
        script: |
          echo "I am $FOO, thanks"
          echo "I am $BAR, thanks"
          echo "sha: $SHA"
          echo "port: $PORT"
          sh test.sh

